# Generated by Django 4.2.23 on 2025-09-02 04:47

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import parler.fields
import parler.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': ' صفحه درباه ما',
                'verbose_name_plural': ' صفحه درباره ما',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutUsPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='تصویر پست')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': ' پست درباه ما',
                'verbose_name_plural': ' پست های درباره ما',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name='نام کامل')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره تماس')),
                ('subject', models.CharField(max_length=150, verbose_name='موضوع')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال')),
                ('is_read', models.BooleanField(default=False, verbose_name='خوانده شده؟')),
            ],
            options={
                'verbose_name': 'پیام ارتباطی',
                'verbose_name_plural': 'پیام\u200cهای ارتباطی',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContactUsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'صفحه تماس با ما',
                'verbose_name_plural': 'صفحه تماس با ما',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FanFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'کارت',
                'verbose_name_plural': 'کارت ها',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='home/', verbose_name='تصویر بنر')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': ' صفحه اصلی',
                'verbose_name_plural': ' صفحه اصلی',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_address_one', models.URLField(blank=True, verbose_name='آدرس اولین پیوندها')),
                ('link_address_two', models.URLField(blank=True, verbose_name='آدرس دومین پیوندها')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/logo/', verbose_name='لوگو')),
                ('mobile_number', models.CharField(blank=True, max_length=50, verbose_name='شماره موبایل')),
                ('telephone', models.CharField(blank=True, max_length=50, verbose_name='شماره تلفن')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='ایمیل')),
                ('instagram', models.URLField(blank=True, verbose_name='اینستاگرام')),
                ('linkedin', models.URLField(blank=True, verbose_name='لینکدین')),
                ('telegram', models.URLField(blank=True, verbose_name='تلگرام')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': 'جزئیات سایت',
                'verbose_name_plural': 'جزئیات سایت',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SettingTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('site_title', models.CharField(blank=True, verbose_name='عنوان جزئیات')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('footer_text', models.TextField(blank=True, verbose_name='متن فوتر')),
                ('link_title_one', models.CharField(blank=True, max_length=40, verbose_name='عنوان اولین پیوندها')),
                ('link_title_two', models.CharField(blank=True, max_length=40, verbose_name='عنوان دومین پیوندها')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.setting')),
            ],
            options={
                'verbose_name': 'جزئیات سایت Translation',
                'db_table': 'core_setting_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='HomeInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('banner_title', models.CharField(max_length=200, verbose_name='عنوان بنر صفحه')),
                ('banner_description', models.TextField(verbose_name='توضیحات بنر صفحه')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.homeinfo')),
            ],
            options={
                'verbose_name': ' صفحه اصلی Translation',
                'db_table': 'core_homeinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FanFactTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('card_title', models.CharField(max_length=100, verbose_name='عنوان کارت')),
                ('card_content', models.TextField(max_length=500, verbose_name='محتوا کارت')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.fanfact')),
            ],
            options={
                'verbose_name': 'کارت Translation',
                'db_table': 'core_fanfact_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ContactUsInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('page_title_one', models.CharField(max_length=200, verbose_name='عنوان صفحه')),
                ('description_one', models.TextField(blank=True, verbose_name='توضیحات صفحه')),
                ('page_title_two', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('description_two', models.TextField(blank=True, verbose_name='توضیحات')),
                ('address', models.TextField(blank=True, verbose_name='آدرس')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='تلفن 1')),
                ('phone_two', models.CharField(blank=True, max_length=50, verbose_name='تلفن 2')),
                ('phone_three', models.CharField(blank=True, max_length=50, verbose_name='تلفن 3')),
                ('phone_four', models.CharField(blank=True, max_length=50, verbose_name='تلفن 4')),
                ('post_code', models.CharField(blank=True, max_length=50, verbose_name='کد پستی')),
                ('fax', models.CharField(blank=True, max_length=50, verbose_name='فکس')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.contactusinfo')),
            ],
            options={
                'verbose_name': 'صفحه تماس با ما Translation',
                'db_table': 'core_contactusinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutUsPostTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('post_title', models.CharField(max_length=200, verbose_name='عنوان پست')),
                ('post_content', models.TextField(verbose_name='محتوا پست')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.aboutuspost')),
            ],
            options={
                'verbose_name': ' پست درباه ما Translation',
                'db_table': 'core_aboutuspost_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AboutUsInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('banner_title', models.CharField(max_length=200, verbose_name='عنوان بنر صفحه')),
                ('banner_description', models.TextField(verbose_name='توضیحات بنر صفحه')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.aboutusinfo')),
            ],
            options={
                'verbose_name': ' صفحه درباه ما Translation',
                'db_table': 'core_aboutusinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
