# Generated by Django 4.2.23 on 2025-09-06 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfotranslation',
            name='meta_description',
            field=models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='contactusinfotranslation',
            name='meta_description',
            field=models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن'),
        ),
        migrations.AddField(
            model_name='homeinfotranslation',
            name='meta_description',
            field=models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن'),
        ),
    ]
