# Generated by Django 4.2.23 on 2025-09-09 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aboutusinfotranslation_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfo',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/'),
        ),
    ]
