# Generated by Django 4.2.23 on 2025-09-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aboutusinfo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfo',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (پیشفرض)'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=20, verbose_name='Meta Robots'),
        ),
        migrations.AddField(
            model_name='contactusinfo',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (پیشفرض)'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=20, verbose_name='Meta Robots'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (پیشفرض)'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=20, verbose_name='Meta Robots'),
        ),
    ]
