# Generated by Django 4.2.23 on 2025-09-16 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_aboutusinfo_meta_robots_contactusinfo_meta_robots_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeinfo',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
        migrations.AlterField(
            model_name='aboutusinfo',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
    ]
