# Generated by Django 4.2.23 on 2025-09-16 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_homeinfo_video_alter_aboutusinfo_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfotranslation',
            name='og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OG'),
        ),
        migrations.AddField(
            model_name='aboutusinfotranslation',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='عکس OG'),
        ),
        migrations.AddField(
            model_name='aboutusinfotranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان OG'),
        ),
    ]
