# Generated by Django 4.2.23 on 2025-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutusinfotranslation_og_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactusinfotranslation',
            name='og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OG'),
        ),
        migrations.AddField(
            model_name='contactusinfotranslation',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='عکس OG'),
        ),
        migrations.AddField(
            model_name='contactusinfotranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان OG'),
        ),
        migrations.AddField(
            model_name='homeinfotranslation',
            name='og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OG'),
        ),
        migrations.AddField(
            model_name='homeinfotranslation',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='عکس OG'),
        ),
        migrations.AddField(
            model_name='homeinfotranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان OG'),
        ),
    ]
