# Generated by Django 4.2.23 on 2025-09-17 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactusinfotranslation_og_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutusinfo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical'),
        ),
        migrations.AddField(
            model_name='contactusinfo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical'),
        ),
        migrations.AddField(
            model_name='homeinfo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical'),
        ),
    ]
