# Generated by Django 4.2.23 on 2025-09-21 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_aboutusinfo_canonical_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='telegram',
        ),
        migrations.AddField(
            model_name='setting',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='فیس بوک'),
        ),
        migrations.AddField(
            model_name='setting',
            name='whatsapp',
            field=models.URLField(blank=True, verbose_name='واتس اپ'),
        ),
    ]
