# Generated by Django 4.2.23 on 2025-09-21 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_setting_telegram_setting_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingLinks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, verbose_name='عنوان پیوند')),
                ('address', models.URLField(blank=True, verbose_name='آدرس پیوند')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='address', to='core.setting')),
            ],
            options={
                'verbose_name': 'گالری تصویر محصولات',
                'verbose_name_plural': 'گالری تصاویر محصولات',
            },
        ),
    ]
