# Generated by Django 4.2.23 on 2025-09-21 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_settinglinks'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settinglinks',
            options={'verbose_name': 'پیوند', 'verbose_name_plural': 'پیوند'},
        ),
        migrations.RenameField(
            model_name='settinglinks',
            old_name='address',
            new_name='link_address',
        ),
    ]
