# Generated by Django 4.2.23 on 2025-09-21 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_settinglinks_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settinglinks',
            name='links',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.setting'),
        ),
        migrations.AlterField(
            model_name='settinglinks',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='عنوان پیوند'),
        ),
    ]
