# Generated by Django 4.2.23 on 2025-09-21 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_settinglinks_links_alter_settinglinks_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='link_address_one',
        ),
        migrations.RemoveField(
            model_name='setting',
            name='link_address_two',
        ),
        migrations.RemoveField(
            model_name='settingtranslation',
            name='link_title_one',
        ),
        migrations.RemoveField(
            model_name='settingtranslation',
            name='link_title_two',
        ),
    ]
