# Generated by Django 4.2.23 on 2025-10-07 12:28

import core.signals
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_remove_setting_link_address_one_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusinfotranslation',
            name='content',
            field=core.signals.CleanedCKEditor5Field(blank=True, verbose_name='محتوا'),
        ),
    ]
