# Generated by Django 4.2.23 on 2025-10-09 08:06

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_aboutusinfotranslation_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='SettingLinksToolbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_image', models.ImageField(blank=True, null=True, upload_to='site/links/', verbose_name='عکس پیوند')),
                ('link_address', models.URLField(blank=True, verbose_name='آدرس پیوند')),
                ('links', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.setting')),
            ],
            options={
                'verbose_name': 'پیوند',
                'verbose_name_plural': 'پیوند',
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='SettingLinksToolbarTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('link_title', models.CharField(blank=True, max_length=100, verbose_name='عنوان پیوند')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='core.settinglinkstoolbar')),
            ],
            options={
                'verbose_name': 'پیوند Translation',
                'db_table': 'core_settinglinkstoolbar_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='SettingLinks',
        ),
    ]
