# Generated by Django 4.2.23 on 2025-09-02 10:17

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import parler.fields
import parler.models
import product.signals


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='تصویر')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('canonical_url', models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical')),
            ],
            options={
                'verbose_name': 'محصول',
                'verbose_name_plural': 'محصولات',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': ' صفحه محصولات',
                'verbose_name_plural': ' صفحه محصولات',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/types/', verbose_name='تصویر شاخص')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('canonical_url', models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='product.product', verbose_name='محصول')),
            ],
            options={
                'verbose_name': 'نوع محصول',
                'verbose_name_plural': 'انواع محصولات',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-types/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.producttype')),
            ],
            options={
                'verbose_name': 'گالری تصویر نوع محصول',
                'verbose_name_plural': 'گالری تصاویر نوع محصول',
            },
        ),
        migrations.CreateModel(
            name='ProductTypeTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('banner_title', models.CharField(default='انواع محصولات', max_length=200, verbose_name='عنوان بنر صفحه')),
                ('banner_description', models.TextField(blank=True, verbose_name='توضیحات بنر صفحه')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('description', product.signals.CleanedCKEditor5Field(blank=True, verbose_name='محتوا')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.producttype')),
            ],
            options={
                'verbose_name': 'نوع محصول Translation',
                'db_table': 'product_producttype_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('banner_title', models.CharField(default='محصولات پترو صنعت تاراز', max_length=200, verbose_name='عنوان بنر صفحه')),
                ('banner_description', models.TextField(blank=True, verbose_name='توضیحات بنر صفحه')),
                ('title', models.CharField(max_length=255, verbose_name='نام محصول')),
                ('description', product.signals.CleanedCKEditor5Field(blank=True, verbose_name='محتوا')),
                ('price', models.CharField(blank=True, max_length=100, verbose_name='قیمت')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.product')),
            ],
            options={
                'verbose_name': 'محصول Translation',
                'db_table': 'product_product_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProductInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('banner_title', models.CharField(max_length=200, verbose_name='عنوان بنر صفحه')),
                ('banner_description', models.TextField(verbose_name='توضیحات بنر صفحه')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='product.productinfo')),
            ],
            options={
                'verbose_name': ' صفحه محصولات Translation',
                'db_table': 'product_productinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
