# Generated by Django 4.2.23 on 2025-09-06 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producttypetranslation',
            name='meta_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
