# Generated by Django 4.2.23 on 2025-09-06 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_producttranslation_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='meta_description',
            field=models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن'),
        ),
        migrations.AlterField(
            model_name='producttypetranslation',
            name='meta_description',
            field=models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن'),
        ),
    ]
