# Generated by Django 4.2.23 on 2025-09-14 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_producttranslation_meta_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (پیشفرض)'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=20, verbose_name='Meta Robots'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (پیشفرض)'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=20, verbose_name='Meta Robots'),
        ),
    ]
