# Generated by Django 4.2.23 on 2025-09-19 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_producttranslation_og_description_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypeimage',
            options={'verbose_name': 'گالری تصویر پروژه', 'verbose_name_plural': 'گالری تصاویر پروژه'},
        ),
    ]
