# Generated by Django 4.2.23 on 2025-09-19 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_producttypeimage_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
    ]
