# Generated by Django 4.2.23 on 2025-09-19 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_product_video_producttype_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producttypeimage',
            options={'verbose_name': 'گالری تصویر انواع محصولات', 'verbose_name_plural': 'گالری تصاویر انواع محصولات'},
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='product.product')),
            ],
            options={
                'verbose_name': 'گالری تصویر محصولات',
                'verbose_name_plural': 'گالری تصاویر محصولات',
            },
        ),
    ]
