# Generated by Django 4.2.23 on 2025-11-02 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0008_alter_producttypeimage_options_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['updated_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
