# Generated by Django 4.2.23 on 2025-11-02 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_alter_product_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-updated_at'], 'verbose_name': 'محصول', 'verbose_name_plural': 'محصولات'},
        ),
    ]
