# Generated by Django 4.2.23 on 2025-09-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_articletranslation_meta_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='meta_description',
            field=models.TextField(blank=True, default='توضیحات سایت', null=True),
        ),
    ]
