# Generated by Django 4.2.23 on 2025-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_articletranslation_meta_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articletranslation',
            name='meta_description',
            field=models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن'),
        ),
    ]
