# Generated by Django 4.2.23 on 2025-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_bloginfotranslation_meta_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='meta_robots',
            field=models.CharField(choices=[('index, follow', 'Index, Follow (پیشفرض)'), ('noindex, follow', 'Noindex, Follow'), ('index, nofollow', 'Index, Nofollow'), ('noindex, nofollow', 'Noindex, Nofollow')], default='index, follow', max_length=20, verbose_name='Meta Robots'),
        ),
    ]
