# Generated by Django 4.2.23 on 2025-09-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_bloginfo_meta_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='video',
            field=models.FileField(blank=True, upload_to='videos/', verbose_name='ویدئو'),
        ),
    ]
