# Generated by Django 4.2.23 on 2025-09-09 11:23

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import parler.fields
import parler.models
import project.signals


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='articles/images/', verbose_name='تصویر شاخص')),
                ('slug', models.SlugField(unique=True, verbose_name='اسلاگ')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی')),
                ('canonical_url', models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال باشد؟')),
                ('created_at', django_jalali.db.models.jDateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('updated_at', django_jalali.db.models.jDateTimeField(auto_now=True, verbose_name='تاریخ بروز رسانی')),
            ],
            options={
                'verbose_name': ' صفحه پروژه',
                'verbose_name_plural': ' صفحه پروژه',
                'ordering': ['-created_at'],
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('meta_description', models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان')),
                ('content', project.signals.CleanedCKEditor5Field(blank=True, verbose_name='محتوای مقاله')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='project.project')),
            ],
            options={
                'verbose_name': 'پروژه Translation',
                'db_table': 'project_project_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ProjectInfoTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('meta_title', models.CharField(default='Petro Sanat Taraz', verbose_name='متا تایتل')),
                ('meta_description', models.TextField(default='توضیحات سایت', verbose_name=' متا دسکریپشن')),
                ('banner_title', models.CharField(max_length=200, verbose_name='عنوان بنر صفحه')),
                ('banner_description', models.TextField(verbose_name='توضیحات بنر صفحه')),
                ('title', models.CharField(blank=True, max_length=200, verbose_name='عنوان')),
                ('content', models.TextField(blank=True, verbose_name='محتوا')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='project.projectinfo')),
            ],
            options={
                'verbose_name': ' صفحه پروژه Translation',
                'db_table': 'project_projectinfo_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
