# Generated by Django 4.2.23 on 2025-09-09 12:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_alter_projecttranslation_content'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product-types/gallery/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='project.project')),
            ],
            options={
                'verbose_name': 'گالری تصویر پروژه',
                'verbose_name_plural': 'گالری تصاویر پروژه',
            },
        ),
    ]
