# Generated by Django 4.2.23 on 2025-09-09 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_projectimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projecttranslation',
            name='banner_description',
            field=models.TextField(blank=True, verbose_name='توضیحات بنر'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='banner_title',
            field=models.CharField(blank=True, verbose_name='عنوان بنر'),
        ),
    ]
