# Generated by Django 4.2.23 on 2025-09-12 16:05

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_projecttranslation_banner_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='محتوای پروژه'),
        ),
    ]
