# Generated by Django 4.2.23 on 2025-09-13 06:18

from django.db import migrations
import project.signals


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0007_alter_projecttranslation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='content',
            field=project.signals.CleanedCKEditor5Field(blank=True, verbose_name='محتوای پروژه'),
        ),
    ]
