# Generated by Django 4.2.23 on 2025-09-13 06:27

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_alter_projecttranslation_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projecttranslation',
            name='content',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='محتوای پروژه'),
        ),
    ]
