# Generated by Django 4.2.23 on 2025-09-17 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_project_meta_robots_projectinfo_meta_robots'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='canonical_url',
            field=models.URLField(blank=True, help_text='اگر خالی باشد، به صورت پیش\u200cفرض همان آدرس صفحه استفاده می\u200cشود.', null=True, verbose_name='آدرس Canonical'),
        ),
        migrations.AddField(
            model_name='projectinfotranslation',
            name='og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OG'),
        ),
        migrations.AddField(
            model_name='projectinfotranslation',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='عکس OG'),
        ),
        migrations.AddField(
            model_name='projectinfotranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان OG'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='og_description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات OG'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='og_image',
            field=models.ImageField(blank=True, null=True, upload_to='og_images/', verbose_name='عکس OG'),
        ),
        migrations.AddField(
            model_name='projecttranslation',
            name='og_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان OG'),
        ),
    ]
