"""
Django settings for petrosanattaraz project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-defaultkey")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parler',
    'django_ckeditor_5',

    'core',
    'product',
    'blog',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petrosanattaraz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'petrosanattaraz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "taraz"),
        "USER": os.getenv("POSTGRES_USER", "tarazuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "petro_pass"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = [
    ('fa', 'فارسی'),
    ('en', 'English'),
    ('ar', 'العربية'),
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'fa'},
        {'code': 'en'},
        {'code': 'ar'},
    ),
    'default': {
        'fallbacks': ['fa'],
        'hide_untranslated': False,
    }
}
LANGUAGE_CODE = 'fa'

PARLER_DEFAULT_LANGUAGE_CODE = 'fa'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': [
            'heading',
            '|',
            'bold',
            'italic',
            'link',
            'underline',
            '|',
            'bulletedList',
            'numberedList',
            'blockQuote',
            '|',
            'imageUpload',
            '|',
            'undo',
            'redo',
        ],
        "link": {
            "addTargetToExternalLinks": True,
            "defaultProtocol": "https://",
            "decorators": {
                "openInNewTab": {
                    "mode": "manual",
                    "label": "Open in a new tab",
                    "attributes": {
                        "target": "_blank",
                        "rel": "noopener noreferrer"
                    }
                }
            }
        },
        'language': 'fa',
        'htmlSupport': {
            'allow': [
                {'name': 'a', 'attributes': ['href', 'target', 'rel', 'title']},
                {'name': 'img', 'attributes': ['src', 'alt', 'width', 'height']},
                {'name': 'h1'}, {'name': 'h2'}, {'name': 'h3'}, {'name': 'h4'}, {'name': 'h5'}, {'name': 'h6'},
                {'name': 'p'}, {'name': 'div'}, {'name': 'span'},
                {'name': 'strong'}, {'name': 'em'}, {'name': 'u'}, {'name': 's'},
                {'name': 'ul'}, {'name': 'ol'}, {'name': 'li'},
                {'name': 'blockquote'}, {'name': 'pre'}, {'name': 'code'},
                {'name': 'table'}, {'name': 'thead'}, {'name': 'tbody'}, {'name': 'tr'}, {'name': 'td'}, {'name': 'th'},
                {'name': 'br'}, {'name': 'hr'}
            ],
            'disallow': [
                {'name': 'script'},  # مسدود کردن تگ اسکریپت
                {'name': 'iframe'},   # مسدود کردن iframe
                {'name': 'object'},  # مسدود کردن object
                {'name': 'embed'},   # مسدود کردن embed
                {'name': 'style'},    # مسدود کردن style
                {'name': 'form'},     # مسدود کردن form
                {'name': 'input'},    # مسدود کردن input
                {'name': 'button'},  # مسدود کردن button
                {'name': 'textarea'}  # مسدود کردن textarea
            ]
        },
        'htmlEmbed': {
            'showPreviews': False,  # غیرفعال کردن پیش نمایش کدهای embed
        },
        'mediaEmbed': {
            'previewsInData': False,  # غیرفعال کردن پیش نمایش رسانه‌ها
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'متن معمولی', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'سرتیتر ۱', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'سرتیتر ۲', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'سرتیتر ۳', 'class': 'ck-heading_heading3'}
            ]
        }
    },
    'extends': {
        'blockToolbar': [
            'paragraph',
            'heading1',
            'heading2',
            'heading3',
            '|',
            'bulletedList',
            'numberedList',
            '|',
            'blockQuote',
        ],
        'toolbar': [
            'heading',
            '|',
            'bold',
            'italic',
            'underline',
            'strikethrough',
            'link',
            '|',
            'fontBackgroundColor',
            'fontColor',
            'fontSize',
            'fontFamily',
            '|',
            'alignment',
            '|',
            'bulletedList',
            'numberedList',
            '|',
            'indent',
            'outdent',
            '|',
            'imageUpload',
            'blockQuote',
            'insertTable',
            'mediaEmbed',
            'codeBlock',
            'htmlEmbed',
            '|',
            'undo',
            'redo',
        ],
        'image': {
            'toolbar': [
                'imageTextAlternative',
                'toggleImageCaption',
                'imageStyle:inline',
                'imageStyle:block',
                'imageStyle:side',
            ],
            'styles': [
                'full',
                'side',
                'alignLeft',
                'alignRight',
                'alignCenter',
            ]
        },
        'table': {
            'contentToolbar': [
                'tableColumn',
                'tableRow',
                'mergeTableCells',
                'tableProperties',
                'tableCellProperties',
            ]
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'متن معمولی', 'class': 'ck-heading_paragraph'},
                {'model': 'heading1', 'view': 'h1', 'title': 'سرتیتر ۱', 'class': 'ck-heading_heading1'},
                {'model': 'heading2', 'view': 'h2', 'title': 'سرتیتر ۲', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'سرتیتر ۳', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'سرتیتر ۴', 'class': 'ck-heading_heading4'},
                {'model': 'heading5', 'view': 'h5', 'title': 'سرتیتر ۵', 'class': 'ck-heading_heading5'},
                {'model': 'heading6', 'view': 'h6', 'title': 'سرتیتر ۶', 'class': 'ck-heading_heading6'}
            ]
        }
    }
}

CKEDITOR_5_UPLOAD_PATH = "uploads/"

