"""
Django settings for petrosanattaraz project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-defaultkey")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'parler',
    'django_ckeditor_5',
    "django.contrib.sitemaps",
    'imagekit',

    'core',
    'product',
    'blog',
    'project',
    'redirects',
]

MIDDLEWARE = [
    'redirects.middleware.RedirectMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'petrosanattaraz.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'core.context_processors.global_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'petrosanattaraz.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": os.getenv("POSTGRES_DB", "taraz"),
        "USER": os.getenv("POSTGRES_USER", "tarazuser"),
        "PASSWORD": os.getenv("POSTGRES_PASSWORD", "petro_pass"),
        "HOST": os.getenv("POSTGRES_HOST", "localhost"),
        "PORT": os.getenv("POSTGRES_PORT", "5432"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGES = [
    ('fa', 'فارسی'),
    ('en', 'English'),
    ('ar', 'العربية'),
]

PARLER_LANGUAGES = {
    None: (
        {'code': 'fa'},
        {'code': 'en'},
        {'code': 'ar'},
    ),
    'default': {
        'fallbacks': ['fa'],
        'hide_untranslated': False,
    }
}
LANGUAGE_CODE = 'fa'

PARLER_DEFAULT_LANGUAGE_CODE = 'fa'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

USE_L10N = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']

STATIC_ROOT = BASE_DIR / "staticfiles"

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CORS_ALLOW_CREDENTIALS = True

#CORS_ALLOW_ALL_ORIGINS = True

# CORS_ALLOWED_ORIGINS = [
#     "http://127.0.0.1:5500",
#     "http://localhost:5500",
#     "http://localhost",
#     "http://127.0.0.1",
#     "https://test-seo.petrosanattaraz.com",
# ]


CSRF_TRUSTED_ORIGINS = [
    "https://test-seo.petrosanattaraz.com",
    "http://test-seo.petrosanattaraz.com",
    "https://petrosanattaraz.com",
    "http://petrosanattaraz.com"
]


USE_X_FORWARDED_HOST = True
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')


CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'png', 'jpg', 'webp']

CKEDITOR_5_CONFIGS = {
    "default": {
        "toolbar": [
            "heading", "|",
            "bold", "italic", "underline", "link",
            "bulletedList", "numberedList", "|",
            "blockQuote", "|",
            "insertTable", "|",
            "insertImage", "|",
        ],
        "image": {
            "toolbar": [
                "imageTextAlternative", "|",
                "imageStyle:alignLeft",
                "imageStyle:alignRight",
                "imageStyle:alignCenter", "|",
            ],
        },
        "table": {
            "contentToolbar": [
                "tableColumn", "tableRow",
                "mergeTableCells", "tableProperties", "tableCellProperties",
            ]
        },

        # 🛡 بخش امنیتی
        "htmlSupport": {
            "allow": [
                {"name": "a", "attributes": ["href", "target", "rel", "title"]},
                {"name": "img", "attributes": ["src", "alt", "width", "height", "style"]},
                {"name": "p"}, {"name": "div"}, {"name": "span", "attributes": ["style"]},
                {"name": "strong"}, {"name": "em"}, {"name": "u"}, {"name": "s"},
                {"name": "ul"}, {"name": "ol"}, {"name": "li"},
                {"name": "blockquote"}, {"name": "pre"}, {"name": "code"},
                {"name": "table"}, {"name": "thead"}, {"name": "tbody"},
                {"name": "tr"}, {"name": "td"}, {"name": "th"},
                {"name": "br"}, {"name": "hr"},
            ],
            "disallow": [
                {"name": "script"},
                {"name": "iframe"},
                {"name": "object"},
                {"name": "embed"},
                {"name": "form"},
                {"name": "input"},
                {"name": "button"},
                {"name": "textarea"},
                {"name": "style"},  # بلاک تگ <style>
            ],
        },
        "htmlEmbed": {
            "showPreviews": False,  # جلوگیری از اجرای کدهای embed
        },
        "mediaEmbed": {
            "previewsInData": False,  # جلوگیری از لود اتوماتیک مدیا
        },
    }
}


CKEDITOR_5_UPLOAD_PATH = "uploads/"
