# Generated by Django 4.2.23 on 2025-10-28 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Redirect',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(help_text='مثلاً: /fa/محصول-قدیمی/', max_length=512, unique=True, verbose_name='آدرس قدیمی')),
                ('new_path', models.CharField(help_text='مثلاً: /fa/new-product/', max_length=512, verbose_name='آدرس جدید')),
                ('active', models.BooleanField(default=True, verbose_name='فعال')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
