# Generated by Django 4.2.23 on 2025-10-28 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='redirect',
            options={'ordering': ['-created_at'], 'verbose_name': 'ریدایرکت', 'verbose_name_plural': 'ریدایرکت ها'},
        ),
    ]
