# Generated by Django 4.2.23 on 2025-11-02 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirects', '0002_alter_redirect_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='redirect',
            name='new_path',
            field=models.CharField(max_length=512, verbose_name='آدرس جدید'),
        ),
        migrations.AlterField(
            model_name='redirect',
            name='old_path',
            field=models.CharField(max_length=512, unique=True, verbose_name='آدرس قدیمی'),
        ),
    ]
